### ISSUE TITLE
Cores data not persisted to correct dir in "test" mode

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#157]
**Describe the bug**

PHP 7.2 + v4.4.3 + Solr 8.20 +  `dev-master#7c78fb8c62618fbd50c926e5772457c827a6f4f0` (If you can convince me the latest build will also fix this issue, I'll update the version - OK, I tried `^1.0-beta3`, different errors: #158)

Uable to save config anywhere _other than_ a local `.solr` dir.

Attempting to use a different dir for storing Solr's core data, defined in YML results in a local `.solr` dir being re-created and populated instead regardless.

**To Reproduce**

Set the site into "test" mode and use the following local YML config, and run the Configure task:

```
---
Name: my-search
After: 'SolrSearch'
---
Only:
  environment:
    - live
    - test
---
Firesphere\SolrSearch\Services\SolrCoreService:
  config:
    endpoint:
      myhostname:
        host: localhost
        port: 8983
        timeout: 10
        # set up timeouts
        index_timeout: 10
        optimize_timeout: 100
        finalize_timeout: 300
        http_method: 'AUTO'
        # commit within 60ms
```

**Expected behavior**

Cores and metadata are persisted to "'/opt/solr/server/solr" and not ".solr"
