### ISSUE TITLE
Unable to run SolrConfigureTask for 1.0-beta3

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#158]
**Describe the bug**

* PHP7.2 + Solr 8.2 + v4.3.3 + Module 1.0-beta3 + Ubuntu Bionic (Vagrant + LXD)y
* Run `sudo ./vendor/bin/sake dev/tasks/SolrConfigureTask`
* Result:

```
ERROR [Emergency]: Uncaught LogicException: No classes or config to index found!
IN GET dev/tasks/SolrConfigureTask
Line 184 in /vagrant/vendor/firesphere/solr-search/src/Indexes/BaseIndex.php
```
My `BaseIndex` subclass has not changed since I used `7c78fb8c62618f`, so the module's API must've changed?

Looking back at `BaseIndex.php` @ `7c78fb8c6261` and I'm non the wiser...

**To Reproduce**

* Install  ^1.0
* Run SolrConfigureTaskl
* Observe errors to do with missing config

**Expected behavior**

No errors.

**Comment by Firesphere** [comment]
Are you using Vagrant?

It might be that I've been a bit too aggressive on phasing out the PHP style config. Even though the tests are working.

Can you please share your code with me, so I can see a bit more clear what might be wrong?

We're actively cleaning up the API at the moment, so it might very well be we're a bit too thorough.

**Comment by Firesphere** [comment]
Please share the way you have set up your config, optionally via email, so we can further look. This should not happen in theory, as that bit of code only had some minor touch-ups and no big changes recently.

**Comment by Firesphere** [comment]
Have you seen the documentation?
https://firesphere.github.io/solr-docs/16-Known-issues.html

**Comment by phptek** [comment]
OK, following the updated docs with ref to using "/var/solr/data", made the errors go away and I can successfully run `dev/tasks/SolrConfigureTask` but following the instructions in the docs for Vagrant boxes, there are a few differences in setup and behaviour:

* Solr is running as the "vagrant" user
* The local ".solr" dir is re-created, but only with the default Elemental index from the module itself

Conditions:

* Vagrant + LXD on Ubuntu Bionic
* Solr 8.2.0 started as a service and is running as the "vagrant" and not "solr" user
* Silverstripe 4.4.3 + Module 1.0-beta3 + PHP7.2
* Followed suggestion for the format of the YML `After` block (although it shouldn't matter, `After` doesn't need to be an array)

Config:

No PHP Index, all set in YML, cache cleared, dev/build run from the CLI

```
---
Name: my-search
After:
  - 'SolrSearch'
---
Only:
  environment:
    - test
    - live
---
Firesphere\SolrSearch\Services\SolrCoreService:
  config:
    endpoint:
      localhost:
        host: localhost
        port: 8983
        timeout: 10
        # set up timeouts
        index_timeout: 10
        optimize_timeout: 100
        finalize_timeout: 300
        http_method: 'AUTO'
        # commit within 60ms
        commit_within: 60
  store:
    mode: 'file'
    path: '/opt/solr/server/solr'
---
Except:
  environment:
    - test
    - live
---
Firesphere\SolrSearch\Services\SolrCoreService:
  config:
    endpoint:
      localhost:
        host: localhost
        port: 8983
        timeout: 10
        # set up timeouts
        index_timeout: 10
        optimize_timeout: 100
        finalize_timeout: 300
        http_method: 'AUTO'
        # commit within 60ms
        commit_within: 60
  store:
    mode: 'file'
    path: '/var/solr/data'

Firesphere\SolrSearch\Indexes\BaseIndex:
  Core_Elemental:
    Classes:
      - DNADesign\Elemental\Models\BaseElement
    FulltextFields:
      - Title
      - forTemplate
      - LeftColumn
      - RightColumn
  Core_Other:
    Classes:
      - SilverStripe\CMS\Model\SiteTree
      - SilverStripe\Assets\File
    FulltextFields:
      - Title
      - Content
      - Intro
    FilterFields:
      - SubsiteID
      - ShowInSearch
```

rm -rf .solr
mkdir -p /var/solr/data/Core_Elemental/conf && mkdir -p /var/solr/data/Core_Elemental/data
mkdir -p /var/solr/data/Core_Other/conf && mkdir -p /var/solr/data/Core_Other/data
sudo chmod -R 777 /var/solr/data/
solr stopped + restarted
`#> ./vendor/bin/sake dev/tasks/SolrConfigureTask` (No errors)

```
sudo ls -al /var/solr/data/Core_Elemental/conf/
total 8
drwxrwxrwx 2 vagrant vagrant 4096 Dec 10 08:13 .
drwxrwxrwx 4 vagrant vagrant 4096 Dec 10 08:13 ..
```

```
#> ls -al . | grep solr
drwxrwxrwx  3 russellmichell    55593      4096 Dec 10 08:29 .solr
```

...and of course SolrIndexTask hangs becuase there's no config

```
./vendor/bin/sake dev/tasks/SolrIndexTask
...
```
