### ISSUE TITLE
(Re)-inroduce userland control of includeSubclasses

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#162]
**Is your feature request related to a problem? Please describe.**

As the title says, I would like to have control over whether or not the module uses, or not, all subclasses of a base class.

The old FTS module allowed classes to be passed directly into a `SearchQuery` instance as an array, with a child value of `'includeSubclasses' => true|false,`.

**Describe the solution you'd like**

Something like this (using valid YML!)

```
...
Catalyst\MyProject\Search\MyIndex:
  MyIndex:
    Classes:
      - SilverStripe\CMS\Model\SiteTree
      - SilverStripe\Assets\File:
          # Index `File` classes, but not `Image` classes
          include_subclasses: false
      - DNADesign\Elemental\Models\BaseElement
    FulltextFields:
      - Title
...
```

The underlying issues (AFAICT) is that `CoreServiceTrait::getClassesInHierarchy()` bakes-in the 2nd param to `FieldResolver::getHierarchy($class, true)` making it always `true`.

[UPDATE] I set this to false and images were still indexed.

**Describe alternatives you've considered**

In PageController.php::results():

```
...
$index = Injector::inst()->create(MyIndex::class);
$query = SearchQuery::create()
    ->setClasses([
        [
            'class' => File::class,
            'config' => ['include_subclasses' => false]
        ]
    ])
    ->setStart($start)
    ->setFields($params[0])
    ->setTerms($params)
    ->setRows(self::$results_per_page)
    ->setExclude($exclusions);
...
```

...but with the above option, I never liked it TBH. Could never tell whether it was overriding what you had built in your `SolrIndex` subclass defs...or not

**Comment by phptek** [comment]
In the meantime I have simply made it an exclusion which seems to work OK, but feels a little bit like a workaround:

```
...
Catalyst\MyProject\Search\MyIndex:
  MyIndex:
    Classes:
      - SilverStripe\CMS\Model\SiteTree
      - SilverStripe\Assets\File:
      - DNADesign\Elemental\Models\BaseElement
    FulltextFields:
      - Title
    FilterFields:
      - ClassName
...
```

Then in `PageController.php`

```
$exclusions = [
    'SiteTree_ShowInSearch' => 0,
    'File_ClassName' => Image::class,
];

$query = SearchQuery::create()
...
        ->setExclude($exclusions);
...
```
