### ISSUE TITLE
Apparent hard coded search term length

### ISSUE THREAD

**Issue by phptek** [Firesphere/silverstripe-solr-search#169]
**Describe the bug**

Searching for terms with 3 chars or fewer, or strings containing words with 3 chars or fewer, results in an exception in `BaseIndex::doSearch()` on line 217 where `$result` is `null`.

**To Reproduce**

1. Search for "Iwi"
2. Observe exception
3. Search for "To"
4. Observe exception
5. Search for "This is a test"
6. Observe exception (Due to tokenisation of each term, where "is" <= 3 chars)
7. Search for "Alan"
8. Observe no exception

**Expected behaviour**

Searching for one or more terms with of 3 or fewer characters, does not yield an exception and returns relevant results. I can do this with and without quotes in the Solr UI without issue.

**Environment**

PHP 7.2 + Bionic (Vagrant / LXD) + Module 2974936ea + Silverstripe 4.4.3

Search Index

```
Catalyst\TRC\Search\TRCIndex:
  MyIndex:
    Classes:
      - SilverStripe\CMS\Model\SiteTree
      - SilverStripe\Assets\File
      - DNADesign\Elemental\Models\BaseElement
    FulltextFields:
      - Title
      - forTemplate
      - LeftColumn
      - RightColumn
      - Content
      - Intro
    FilterFields:
      - SubsiteID
      - ShowInSearch
      - ClassName
```
Query Construction

```
$params = [[
    'text' => $keywords, // <-- e.g. Random Page Title OR "Random Page Title"
    'fuzzy' => false,
    'boost' => false,
]];

$query = SearchQuery::create()
        ->setClasses(self::$classes_to_search)
        ->setStart($start)
        ->setFields($params[0])
        ->setTerms($params)
        ->setRows(100)
        ->setExclude($exclusions)
```
