### ISSUE TITLE
Module doesn’t support authentication

### ISSUE THREAD

**Issue by kinglozzer** [Firesphere/silverstripe-solr-search#218]
E.g: https://lucene.apache.org/solr/guide/8_5/basic-authentication-plugin.html

Example yaml config:

```yml
Firesphere\SolrSearch\Services\SolrCoreService:
  config:
    endpoint:
      localhost:
        username: 'solr'
        password: 'SolrRocks'
```

Most of the module does work if you hack around the parts that don’t work. These are:

- [`SolrCoreService::getSolrVersion()`](https://github.com/Firesphere/silverstripe-solr-search/blob/87dbf70/src/Services/SolrCoreService.php#L288-L322)
- [`SolrLogger`](https://github.com/Firesphere/silverstripe-solr-search/blob/87dbf7045577b8b256b86b17ecbb95c1dcfae2b7/src/Helpers/SolrLogger.php#L41-L57)

I’m not sure if it’s best to try to hack in some auth into these specific cases, or try to make them use the main `Solarium` instance that does support auth.
